# Generated by Django 5.0.1 on 2024-01-05 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sala', models.IntegerField(primary_key=True, serialize=False)),
                ('capacidade', models.IntegerField()),
                ('edificio', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('andar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReservedSala',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoCalendarizacao.sala')),
            ],
        ),
    ]
